= Conclusion

The first part of this thesis explores with a rational praxeological analysis the axiom of scarcity and non-scarcity as the fundamental per-requisite of the realm of human action. Individuals live in a world filled with scarce and non-scarce goods and both can be used to satisfy desires. Yet human action only applies to the allocation of scarce resources throughout time. Scarce goods are exclusive, meaning that only one individual can at any time fully use the good, as well as rare, meaning that there is a limited supply of the means to satisfy only a limited number of ends. Without this universal limitation there would be no need and justification for individuals manifesting themselves in this world. 

Scarcity is a solid foundation for the praxeological analysis to explore the two different forms of interaction, the voluntary mutually beneficial economic means, and the aggressive exploitative political means. On the one side is Liberty, where free individuals have the property rights in themselves, as well as their homesteaded and exchanged goods. The agora is based on the mutually beneficial trade of scarce goods so that both parties increase their subjective marginal preferences. The polar opposite is slavery, where a master initiates aggressive force against the private property of a slave. Since this is not a voluntary action, it is praxeological proof that only the tyrant is increasing his value scale, while the victim is suffering a reduction in his well-being.

The other side of this axiom is non-scarcity of goods. These are either non-exclusive, so that the use by one individual does not prohibit the use of another, or abundant, in the sense that there is enough for everyone to satisfy their desire. Non-scarcity is evident in the realm of mind and cyberspace, where knowledge can be shared freely without the need of sacrifice of the inventor. Information can be perfectly copied and instantly shared with whomever it might be valuable for only a minuscule amount of computational energy. This is especially the case for libre open source software, since the user has full access to run the code, he can copy and distribute it, as well as study, change and improve the non-scarce software. This is in stark contrast with the fallacious claims of intellectual property rights, where the creator utilizes state aggression in order to create artificial scarcity for the knowledge he has created. Any form of this ownership claim in knowledge is not just logically infeasible, but especially destructive and an unjustifiable limitation to humankind.

Cryptography is a brilliant use of non-scarce information in order to create exclusive knowledge of a secret, with mathematical proof of existence without revealing the secret itself. Since a private key is simple a non-scarce large random number, there is no need for property rights to allocate it. A proper use of private public key cryptography requires that the knowledge of the secret is kept occulted by the individual who is using it. However, this is an artificial exclusivity and is easily broken by simply copying the private key, without taking it from the original creator. Bitcoin uses a vast array of different non-scarce protocols and software in order to emerge cryptographically proven scarcity of bitcoin. One exclusive UTXO is at any time always locked up by only one script, and only he who can produce a valid witness has the ability to spend the coin. The halvening limits the supply of new bitcoin being created, thus establishing the rarity of the libre sound money. Full nodes define, verify and enforce the Nakamoto consensus protocol, and thus full nodes create and secure the scarcity of UTXOs.

Part two details and summarizes the different cryptographically protocols and scripts that define and enforce the property rights of bitcoin. The Bitcoin scripting language is used to commit an exclusive locking script at the time of creating the coin. Only with a valid solution to this script, and nothing else, can the bitcoin be send to another script. This can be as basic as a single public key and signature, here the coin is in the exclusive ownership of the first individual to prove knowledge of the private key. Yet there are further capabilities of the scripting language to describe more precise property right definitions.

The command OP_CHECKMULTISIG specifies `n` public keys in the redeem script, and requires `m` signatures of these keys in the witness script. One individual alone can not spend the coin, but he always requires the collaboration of `m` signers. Thus one alone has no exclusive ownership of the coin, rather a shared ownership amongst any group of `m` individuals. This spending condition is verified and enforced explicitly by full nodes.

Another technology to achieve a similar end is the Schnorr signature scheme, which due to its linearity enables many possibilities to define shared ownership. `N` individual public keys are aggregated into one single public key which is committed to the time chain in the redeem script of a single signature UTXO. A valid signature can only be produced when `n` individual private keys sign the same message interactively in order to produce one single aggregated signature. Taproot is a new script verification protocol that enables the structure of several redeem scripts in a tree structure for a reduction of data size committed to the chain and increased privacy. One basic use of taproot is a brilliant setup of a `m-of-n` threshold scheme that is actually a tree with several individual `m-of-m` scripts, so that any `m-of-n` can produce a valid witness.

Shamir's Secret Sharing is a protocol used to divide a given master secret `MS` into `n` shares, where knowledge of `m` shares is required in order to calculate the master secret again. Although the `n` peers have each exclusive knowledge of their `n` shares, they alone have no knowledge whatsoever about the `MS`. Yet the master dealer has knowledge of `MS`, thus this scheme is not a true non-simulated shared ownership setup. Yet it can be used in conjunction with other protocols like Schnorr to enable non-simulated `m-of-n` threshold ownership of a UTXO.

The lightning network consists of several individual payment channels to update the current state of property rights of a UTXO off-chain without verification by all full nodes. The current implementation of these payment channels is a `2-of-2` multisig between the channel peers, with several partially signed commitment transactions that spend this multisig into the individual scripts. This is a complex setup of several transactions with signatures, hashed time locked contracts and revocation secrets. Yet this concept of a `2-of-2` payment channel can be expanded to create a `n-of-n` channel factory that creates many individual `2-of-2` payment channels off-chain. Lightning network is one of the well thought out implementations of non-simulated shared ownership of scarce bitcoin, yet there are countless more use cases.

Multi signatures can be used to solve for countless in the context of security, collaboration and exchange. In the case that one individual has control of all `n` keys, then this is a second-factor defense against the leaking of any `m-1` keys. This can be further straightened by giving `m-1` keys to a semi-trusted security specialist to verify specified spending conditions before co-signing a transaction. It can also be used to manage shared funds in a collaborative project, so that only a subset of participants needs to agree to a spend, and one individual alone can not go rogue and steal the funds. One of the most powerful use cases is the trustless execution of a `2-of-3` escrow for the exchange of other goods. Here the merchant gains a proof of fund before the good is exchanged, and the buyer gains the ability to verify the goods before ultimately settling the payment.

To conclude, bitcoin is libre sound money, defined, verified and enforced by individual sovereign full nodes. With a brilliant application of non-scarce cryptography and open source software, Bitcoin emerges cryptographically proven non-simulated shared ownership of a scarce UTXO. This technology can be used by individuals to support their desire to remove uneasiness by allocation scarce resources throughout time. 
