= Research

Here is a some what random list of interesting papers, articles, tweetstorms, memes, whatever is of interest. 


== Multiparty ECDSA

Fast Multiparty Treshold ECDSA, Rosario Gennaro & Steven Goldfeder: https://dl.acm.org/citation.cfm?id=3243859

Fast Secure Multiparty ECDSA, Yehuda Lindell & Ariel Nof & Samuel Ranellucci: https://eprint.iacr.org/2018/987.pdf

Fast Multiparty Threshold ECDSA, Rosario Gennaro & Steven Goldfeder: https://eprint.iacr.org/2018/987.pdf

Two party signing ECDSA, Stepan Snigirev: https://medium.com/cryptoadvance/ecdsa-is-not-that-bad-two-party-signing-without-schnorr-or-bls-1941806ec36f

Scriptless Scripts with ECDSA, Pedro Moreno-Sanchez & Aniket Kate: https://lists.linuxfoundation.org/pipermail/lightning-dev/attachments/20180426/fe978423/attachment-0001.pdf

Signature aggregation, Greg Maxwell: https://bitcointalk.org/index.php?topic=1377298.0


== Schnorr

Schnorr Multi Signatures, Gregory Maxwell & Andrew Poelstra & Yannick Seurin & Pieter Wuille: https://eprint.iacr.org/2018/068.pdf

Taproot Schnorr SIGHASH_NOINPUT, Pieter Wuille: https://www.youtube.com/watch?v=YSUVRj8iznU

Schnorr signatures for Bitcoin, Pieter Wuille: https://www.youtube.com/watch?v=_Z0ID-0DOnc&feature=youtu.be&t=2297

Future multisignatures, Greg Maxwell: https://www.youtube.com/watch?v=TYQ-3VvNCHE

BIP Schnorr: https://github.com/sipa/bips/blob/bip-schnorr/bip-schnorr.mediawiki

Schnorr implementation, Pieter Wuille: https://github.com/sipa/secp256k1/blob/968e2f415a5e764d159ee03e95815ea11460854e/src/modules/schnorr/schnorr.md

Schnorr improvement to Bitcoin, Stepan Snigirev: https://medium.com/cryptoadvance/how-schnorr-signatures-may-improve-bitcoin-91655bcb4744

Schnorr signatures BIP, mailing list: https://github.com/sipa/secp256k1/blob/968e2f415a5e764d159ee03e95815ea11460854e/src/modules/schnorr/schnorr.md
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2018-July/016211.html
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2018-July/016215.html

Schnorr BLS ECDSA, Dan Boneh: http://diyhpl.us/wiki/transcripts/2016-july-bitcoin-developers-miners-meeting/dan-boneh/

Schnorr technology roadmap, Bitcoin Core: https://bitcoincore.org/en/2017/03/23/schnorr-signature-aggregation/

Schnorr BLS ECDSA, CoreDev.tech: https://bitcoincore.org/logs/2016-05-zurich-meeting-notes.html

Schnorr Signatures, Patrick Strateman: https://elementsproject.org/features/schnorr-signatures

Schnorr, Bitcoin OpTech # 3: https://bitcoinops.org/en/newsletters/2018/07/10/

Schnorr vs ECDSA, Q&A Pieter Wuille: https://bitcoin.stackexchange.com/questions/77234/schnorr-vs-ecdsa/77235#77235

Schnorr batch validation: Q&A Pieter Wuille: https://bitcoin.stackexchange.com/questions/80698/schnorrs-batch-validation/80702#80702

Implications of Schnorr, Q&A GMax & Murch & Adam Back: https://bitcoin.stackexchange.com/questions/34288/what-are-the-implications-of-schnorr-signatures/35351#35351


== BLS

Short signatures from the Weil pairing, Dan Boneh Ben Lynn Hovav Shacham: https://www.iacr.org/archive/asiacrypt2001/22480516.pdf

BLS better than Schnorr, Stepan Snigirev: https://medium.com/cryptoadvance/bls-signatures-better-than-schnorr-5a7fe30ea716


== Lightning Routing

Anonymous Multi-Hop Locks for Blockchain Scalability and Interoperability, Giulio Malavolta & Pedro Moreno-Sanchez & Clara Schneidewind & Aniket Kate & Matteo Maffei: https://lists.linuxfoundation.org/pipermail/lightning-dev/attachments/20180426/fe978423/attachment-0001.pdf


== MimbleWimble

Mimblewimble, Tom Elvis Jedusor: https://scalingbitcoin.org/papers/mimblewimble.txt

Mimblewimble team mailing list: https://lists.launchpad.net/mimblewimble/msg00086.html


= Support

I especially thank the many peers that have supported me in my path towards understanding this complex topic.

Adam Fiscor
Andreas Antonopolous
Alex Brosworth
Gregory Maxwell
Jeff Gallas
Justin Carter
Jonas Nick
Konstantin Nick
Murch
Nicolas Dorier
Pieter Wullie
Rene Pickhardt
Olaoluwa Osuntokun