= Research

Here is a some what random list of interesting papers, articles, tweetstorms, memes, whatever is of interest. 


== Multiparty ECDSA

Gennaro, R., Goldfeder S., (2018). Fast Multiparty Treshold ECDSA. Toronto: Computer and Communications Security. https://dl.acm.org/citation.cfm?id=3243859

Lindell, Y., Nof, A., Ranellucci, S. (2018). Fast Secure Multiparty ECDSA. Toronto: Computer and Communications Security. https://eprint.iacr.org/2018/987.pdf

Snigirev, S. (2018). Two party signing ECDSA. https://medium.com/cryptoadvance/ecdsa-is-not-that-bad-two-party-signing-without-schnorr-or-bls-1941806ec36f

Kate, A., Moreno-Sanchez, P. (2018) Scriptless Scripts with ECDSA. San Diego: Network and Distributed System Security. https://lists.linuxfoundation.org/pipermail/lightning-dev/attachments/20180426/fe978423/attachment-0001.pdf

Maxwell, G. (2016) Signature Aggregation for Improved Scalability. Bitcoin Talk Forum. https://bitcointalk.org/index.php?topic=1377298.0


== Schnorr

Maxwell, G., Poelstra, A., Seurin, Y., Wuille, P. (2018) Schnorr Multi-Signatures with Applications to Bitcoin. https://eprint.iacr.org/2018/068.pdf

Wuille, P. (2018) Taproot, and Schnorr, and SIGHASH_NOINPUT. San Francisco: Bitcoin Developers Meetup. https://www.youtube.com/watch?v=YSUVRj8iznU

Maxwell, G. (2018) Taproot: Privacy preserving switchable scripting. Bitcoin Mailing List. https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2018-January/015614.html

Wuille, P. (2016) Schnorr signatures for Bitcoin. Milan: Scaling Bitcoin. https://www.youtube.com/watch?v=_Z0ID-0DOnc&feature=youtu.be&t=2297_ 


Maxwell, G. (2015) A Deep Dive with Bitcoin Core Developer Greg Maxwell. San Francisco: Bitcoin Devs Seminar. https://www.youtube.com/watch?v=TYQ-3VvNCHE

Casatta, R., Nick, J., Troelsen, J., Turner-Arthur, J., Ruffing, T., Provoost, S., Virial, V., Wuille, P., Williams, A. (2018) BIP Schnorr. https://github.com/sipa/bips/blob/bip-schnorr/bip-schnorr.mediawiki

Wuille, P. (2018) Schnorr implementation. https://github.com/sipa/secp256k1/blob/968e2f415a5e764d159ee03e95815ea11460854e/src/modules/schnorr/schnorr.md

Snigirev, S. (2018) How Schnorr Signatures may improve Bitcoin. https://medium.com/cryptoadvance/how-schnorr-signatures-may-improve-bitcoin-91655bcb4744

O'Conner R. (2018) Schnorr signatures BIP. bitcoin-dev mailing list: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2018-July/016211.html

Aronesty, E. (2018) Multiparty signatures. bitcoin-dev mailing list: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2018-July/016215.html

Boneh, D. (2016) A Conversation with Dan Boneh about Schnorr, BLS, & ECDSA. Stanford: Bitcoin Developers Miners Meeting. http://diyhpl.us/wiki/transcripts/2016-july-bitcoin-developers-miners-meeting/dan-boneh/

Bitcoin Core (2017) Technology Roadmap - Schnorr Signatures and Signature Aggregation. https://bitcoincore.org/en/2017/03/23/schnorr-signature-aggregation/

Bitcoin Core (2016) Schnorr BLS ECDSA. Zurich: CoreDev.tech Meeting: https://bitcoincore.org/logs/2016-05-zurich-meeting-notes.html

Strateman, P. (2018) Schnorr Signatures. Elements Project. https://elementsproject.org/features/schnorr-signatures

Harding, D., Lee, S., Jachymiak, M., O'Beirne, J., Newbery, J. Schmidt, M. (2018) Schnorr Signature. Bitcoin Operations Technology Group: https://bitcoinops.org/en/newsletters/2018/07/10/

Knoblock, L., Wuille, P. (2018) Schnorr vs ECDSA. Bitcoin Stack Exchange. https://bitcoin.stackexchange.com/questions/77234/schnorr-vs-ecdsa/77235#77235

Wuille, P., Jon (2018) Schnorr Batch Validation. Bitcoin Stack Exchange. https://bitcoin.stackexchange.com/questions/80698/schnorrs-batch-validation/80702#80702

Back, A., Friedenbach, M., Harding, D., Troelsen, J. (2015) What are the Implications of Schnorr Signatures. Bitcoin Stack Exchange. https://bitcoin.stackexchange.com/questions/34288/what-are-the-implications-of-schnorr-signatures/35351#35351


== BLS

Boneh, D., Lynn, B., Shacham, H. (2017) Short signatures from the Weil pairing. Standford: Computer Science Department. https://www.iacr.org/archive/asiacrypt2001/22480516.pdf

Snigirev, S. (2018) BLS Signatures: Better than Schnorr. https://medium.com/cryptoadvance/bls-signatures-better-than-schnorr-5a7fe30ea716


== Lightning Network

Poon, J., Dryja, T. (2016) The Bitcoin Lightning Network: Scalable Off-Chain Instant Payments. https://lightning.network/lightning-network-paper.pdf

Decker, C., Russel, R., Osuntokun, O. (2017) Eltoo: A Simple Layer 2 Protocol for Bitcoin. https://blockstream.com/eltoo.pdf

Burchert, C., Decker, C., Wattenhofer, R. (2017) Scalable Funding of Bitcoin Micropayment Channel Networks. Boston: 19th International Symposium on Stabilization, Safety, and Security of Distributed Systems. https://www.tik.ee.ethz.ch/file/a20a865ce40d40c8f942cf206a7cba96/Scalable_Funding_Of_Blockchain_Micropayment_Networks%20(1).pdf

Malavolta, G., Moreno-Sanchez, P., Schneidewind, C., Kate, A., Maffei, M. (2019) Anonymous Multi-Hop Locks for Blockchain Scalability and Interoperability. San Diego: Network and Distributed System Security.  https://eprint.iacr.org/2018/472.pdf

Poon, J. (2016) 2-of-3 Instant Escrow, or How to Do "2-of-3 Multisig Contract" Equivalent on Lightning. Lightning-dev Mailing List. https://lists.linuxfoundation.org/pipermail/lightning-dev/2016-January/000403.html

Lightning Network Specifications (BOLT). https://github.com/lightningnetwork/lightning-rfc

BitcoinJ (2017) Working with Micropayment Channels. https://bitcoinj.github.io/working-with-micropayments

Friedenbach, M. BtcDrak, Dorier, N., Kinoshitajona (2015) BIP 68: Relative Lock-Time Using Consensus-Enforced Sequence Numbers (OP_CSV). https://github.com/bitcoin/bips/blob/master/bip-0068.mediawiki

Friedenbach, M., BtcDrak, Lombrozo, E. (2015) BIP 112: CHECKSEQUENCEVERIFY. 
https://github.com/bitcoin/bips/blob/master/bip-0112.mediawiki

Friedenbach, M., O'Dell, N., Schnelli, J. (2015) What does OP_CHECKSEQUENCEVERIFY Do? Bitcoin Stack Exchange. https://bitcoin.stackexchange.com/questions/38845/what-does-op-checksequenceverify-op-csv-do/38846#38846


== Overall

Nakamoto, S. (2008) Bitcoin: A Peer-to-Peer Electronic Cash System. https://bitcoin.org/bitcoin.pdf

Antonopoulos, A. (2018) Mastering Bitcoin. 2nd ed. Sebastopol: O'Reilly. https://github.com/bitcoinbook/bitcoinbook

Dorier, N., Fiscor, A. (2016) Programming The Blockchain in C#.

Andresen, G., (2012) BIP 16: Pay to Script Hash. https://github.com/bitcoin/bips/blob/master/bip-0016.mediawiki 


== Mimblewimble

Jedusor, T. (2016) Mimblewimble.  https://scalingbitcoin.org/papers/mimblewimble.txt

Poelstra, A. (2017) Lightning in Scriptless Scripts. Mimblewimble Team Mailing List. https://lists.launchpad.net/mimblewimble/msg00086.html


== Acknowledgement

I thank the many peers that have supported me in my path towards understanding this complex topic. Especially I am thnankful for the countless hours Jonas Nick has sacrificed in order to initiate myself in the magic of cryptography. I greatly appreciate the teachings of Stephan Kinsella who has fundamentally realigned my axioms in order to grow a mindset with scarcity at it's core.

6102 Bitcoin, Adam Back, Adam Fiscor, Adam Gibson, Andreas Antonopolous, Andrew Poelstra for your brilliant explanation of advanced magic, Alex Brosworth, Chris Belcher, David Harding for the invaluable knowledge you share through OpTec, Edmond Belliveau, Eric Voskuil for challanging myself to always be consistent, Giacomo Zucco, Gregory Maxwell, Hans Hermann Hoppe, Jeff Gallas, Justin Carter, John Newbery, Joseph Poon, Konstantin Nick, KZen Research, Lucas Ontivero, Ludwig von Mises, Manfred Karrer, Manuel Polavieja, Mark Erhardt, Marek Palatinus, Max Keidum, Murray Rothbard, Nicolas Dorier, Pavol Rusnak, Peter Gray, Pieter Wullie, Rene Pickhardt, Olaoluwa Osuntokun, Omer Shlomovits, Sjors Provoost, Stepan Snigirev.

These are only a few peers who have directly supported the writing of this thesis, be it through high level conversations, detailed write-ups or fixing typos and structure. I thank the entire Bitcoin tribe for fostering the brightest and kindest hodlers of last resort. Vires in numeris.

After rigorous peer review of several drafts of this thesis, any errors in the published version are the fault of the author.
