= Scarcity

This chapter explains the fundamental reason Why multi signature transactions are one of the breathtaking innovations in Bitcoin. The holistic combination of all the nuances in this consensus network emerge a good which has properties like we have never seen before. Bitcoin brilliantly intermingles attributes of both scarcity and non-scarcity to emerge true shared ownership of a scarce good. footnote:[Hillebrand (2018), [Anarchy in Money](https://towardsliberty.com//anarchy/) and the chapter on [Scarcity](https://github.com/MaxHillebrand/Anarchy-in-Money/blob/master/Scarcity.asciidoc).]

== Scarcity

When Alice holds a gold coin in her hand, she has full control over it and can use it throughout time and space. At the same time, Bob can not have the same coin and do something different with it. It's either Alice, or Bob, who can enjoy the experience of having the gold coin at their full disposal, but not both of them at the same time. There is a potential of conflict over who can use the gold coin, and we need economic and moral rules that guide our actions in such conditions. The function of propert rights is to mitigate interpersonal conflict by defining one specific and exclusive owner of each scarce resource. _“Only because scarcity exists is there even a problem of formulating moral laws; insofar as goods are superabundant (‘free’ [non-scarce] goods), no conflict over the use of goods is possible  and  no  action-coordination is needed”_ footnote:[Hoppe, (1989) Theory of Socialism and Capitalism, p.158, n.120.] Scarcity applies to anything and everything that cannot be simultaneously owned, one's ownership excludes others. This is an unwavering natural constraint on these economic goods. 

Because only one individual alone can at any time use the scarce good, there needs to be an economic and moral principle of property rights to allocate the resources to their rightful owner. These property rights must be both visible and just, since otherwise they could not function their task to mitigate conflict. One individual can only know that a specific good is owned by another, if he has advertised this clearly and visibily. Thus, the definition of property rights must be univeral, objective and unambigous. footnote:[Hillebrand, (2018). Anarchy in Money, Chapter 1 on Natural Law.]

Scarce resources are abundant in nature and the first individual to occupy a good and intermingle his human ingenuity to create higher order goods has homesteaded it and thus acquired the just property rights. _Whatsoever, then, he removes out of the state that Nature hath provided and left it in, he hath mixed his labor with it, and joined to it something that is his own, and thereby makes it is property._ footnote:[Locke, (1689) The Two Treatises of Government.]

Since property rights mean that the good is at the full desposal of the individual, he can exchange the right to use these goods with one another. footnote:[See Rothbard (1964) Man Economy and State With Power and Markets, Chapter 2 Part 4 Terms of Exchange.] When two peers are exchanging scarce resources, Alice is sacrificing her property in that gold coin, she is giving up the current and future enjoyment and prosperity of that good. In order to compensate her for this loss, she will want to have something in return, a good or service being offered by Bob. And only when she values that exchanged good marginally higher than she values that gold coin, will she voluntarily agree to the trade. The same is true for Bob, but in reverse order. He will only trade if the gold coin is of higher marginal subjective value than the good he is sacrificing. Only because of this asymmetry of needs and desires will the two peers voluntarily choose to trade their goods, and only then it is mutually beneficial.

Homesteading and mutually beneficial voluntary exchange are the only ways of justly acquiring the property rights in a scarce good. Anyone who is aggressively and without consent taking away a justly acquired good from another, is politically breaking private property rights in that scarce good. 

_"The argument for property rights is based [...] on the need of individuals to employ means to achieve ends, and to avoid interpersonal conflict over such means. This scarcity is [...] a necessary background condition that must obtain before property rights can emerge."_ footnote:[Kinsella (2008) Against Intellectual Property, p. 40.] Scarcity is the fundamental pre-requisite of any money, as there can not be a store of value, medium of exchange and unit of account without property rights, as this good could be copied ad infinitum.

== Non-Scarcity

The other manifestation of this attribute is non-scarcity, goods that can be copied ad infinitum without degrading the quality of the original. footnote:[See Kinsella, (2008) Against Intellectual Property.] Due to this super-abundance these good are not subject to desire and choice, as they exist in superfluity, they gratify and also satisfy all desires which depend on their use. footnote:[See Fetter, (1915) Economic Principles, Chapter 1, §3.]

When based on her previous experiences Alice formulates a thought, and speaks this into existence to Bob, this information forces itself into Bob's possession. He can now contemplate what Alice is trying to convey and act upon the information. Alice still has her "original" idea in mind, nothing has been taken away from her. Rather, She can now accumulate new information based on Bob's reaction to her. _“When speaking words, they can be taken all to oneself, yet leave all to others and unless the memory fades away, everyone who can hear those words, can take them all and go on each separate way.”_ footnote:[Wills, (1999) St. Augustine, p. 145.]

As there is no potential conflict of control, there is no need to organize the structure of production with these non-scarce goods, because any entrepreneur who would need the good to advance the process could simply copy it. There does not need to be a direct exchange, because the original creator does not give up anything, he still retains his version without any sacrifice. _"But sharing isn't immoral — it's a moral imperative. Only those blinded by greed would refuse to let a friend make a copy."_ footnote:[Swartz, (2008) Guerilla Open Access Manifesto.] “These  designs – the  recipes, the formulas, the ideologies – are the primary thing; they transform the original factors – both human and nonhuman – into means.”_ footnote:[Mises, (1949) Human Action, p. 142.]

Because there is no need to ration the allocation of non-scarce goods, property rights do not emerge. There is no individual ownership of ideas, recipes or music, rather, anyone who is interested can acquire and use this information without taking it from some one else. Information belongs in the universal field of knowledge from where any individual can draw everything needed to understand the truth and apply it in ones life. 

=== Non-Scarcity in Cryptography and Bitcoin

A cryptographic private key is a very large random number, a piece of non-scarce information which can be copied endlessly without degrading the original. The potential number field is so large that when one sufficiently random number is picked, it can be assumed that nobody else has knowledge of this specific information. Whoever has the knowledge of this private key can easily compute a corresponding public key and signature. But with only the public key, it is computationally infeasible to calculate the private key. Asymmetric cryptography assumes that the creator of the private key can keep the bits hidden and occulted from anyone else. Only when this knowledge is exclusively available to the original creator is the signature a conclusive prove of identity and intent.

A Bitcoin unspent transaction output [UTXO] can only be spend when the corresponding redeem script is returned valid, these conditions are expressed in the non-Turing-complete Bitcoin script language. At any time, a UTXO has only one script which commits to the spending conditions, the property right definitions of that bitcoin. Thus, there is a potential conflict over who can use this UTXO, it's either the script of Alice, or that of Bob. For example a pay to witness public key hash [P2WPKH] UTXO can only be spent by he who has the knowledge of the committed private key and proves this with a valid signature. Possession of the non-scarce information is sufficient to use the absolutely scarce bitcoin. Although nobody owns information of the private key, its knowledge grants the right to own and use this specific coin. Because the private key can be shared with others without taking the knowledge from someone else, the access rights to the bitcoin can be shared as well. However, with the single key P2WPKH script, only the first individual to broadcast a valid transaction has full control over the bitcoin on chain. Thus, sharing the same private key with others is only a weak simulation of shared ownership.

Pay to witness script hash [P2WSH] transactions commit to more advanced scripts that can add complexity to the conditions that the spender needs to prove. Such a script could be a multi signature scheme, where n private keys are generated and the public keys are included in the redeem script. Only with signature prove of knowledge of m private keys can the UTXO be spent. N individuals can create their own unique private keys, however, this piece of information alone is worthless, as it cannot be used by it self. Only with the coordination of m individuals can the chain of digital signatures be advanced. This is non-simulated shared ownership of the scarce bitcoin which is cryptographically proven and cannot be broken.

== Double Spending is the Non-Scarcity

The double spending problem is defined as the aspect of a digital asset to be able to be send several times to different individuals. First, Alice initiates a transaction to Bob, and right after, she send the same asset to Charlie. The main issue is to find a common state of the most current property right definitions, the Byzantines Generals Problem. Bitcoin solves this computer science problem in a decentralized trustless way.

In other words, the ability to spend the same good twice, means that Alice can give a good to Bob, whithout sacrificing the posession and usage of that good. Thus, this good is non scarce and does not require property rights to allocate resources. Any non scarce good can thus be double spend, while this is impossible for any scarce asset.


== Bitcoin Halvening and Scarcity

Every 210 000 blocks, the issuance rate of new bitcoin in the coinbase transaction is halfed from the origial 50 bitcoin reward. This means that over time, the stock to flow ratio increases exponentially, until it reaches infinity in the year 2141. It is important to differentiate that this does not at all affect the scarcity of bitcoin. Regardless the quantity of total money supply, one UTXO can only be spend by the one defined script. This is true in the case of a total money supply of 50, 21 million or 84 billion bitcoin. The total supply of money does not matter, since prices will simply adjust to reflect the market demand of holding money in percentage to the total money supply. The axiomatic importance is the fact that one UTXO can only be spend by one script, and not two different scripts at the same time.


== Fallacy of Intellectual Property

There are currently seveal different types of "intellectual property" [patents, licenses, non disclosure agreements, ...]. They all claim that the "creator" of a specific idea, receipe or thought are to be the sole beneficiary of it. Anyone who is using this idea on its own, without the explicit consent of the "original thinker" is breaking their property rights and thus punishment is justified and desired. 

Of course this is flaut on a fundamental level. All forms of intellectual creations are per definition non scarce, that is that when the information is shared with others, the "original" producer does not sacrifice the enjoyment of the thought. Precisely because there is no need for resource allocation, there is no need for property rights. IP thus tries to introduce artificiall scarcity in a place where nature has granted us non scarcity! This is an unnecessary limit on the prosperity humans can achieve.

Furthermore, because this bogus claim to establish property rights where we do not need them, innocent individuals get violeted in their legit property rights. If Alice comes up with the idea to bake an apple cake, and she registeres heir IP claim, when Bob on his own finds out the same recipe, he has not taken anything away from Alice. But because Alice has the power of the State, she can enforce her wrong IP claim an steal the cake from Bob. She has no property right whatsoever in the goods and services that Bob has produced on his own, yet with IP, she can justify her aggressiona gainst a peaceful individual.

_"Natural scarcity is that which follows from the relationship between man and nature. Scarcity is natural when it is possible to conceive of it before any human, institutional, contractual arrangement. Artificial scarcity, on the other hand, is the outcome of uch arrangements. Artificial scarcity can hardly serve as a justification for the legal framework that causes the scarcity. Such an argument would be completely circular. On the contrary, artificial scarcity itself needs a justification."_ footnote:[Bouckaert, What is Property? p. 793.] Thus, any form of "intellectual property", be it patents, copyrights or trade marks are completely unjustifiable monopolies of state aggression, privilege and censorship. They are evil to its fundamental core, since it introduces an artificial limit to the potential prosperity humankind might achieve, at the benefit of only a few, but at the expense of many. Those that violently enforce unjust intellectual property, assert control and ownership over some one elses property in scarce resources.
