= PART I: On Scarcity

To understand a non-trivial subject fundamentally, we start with an analysis of its axioms. The basis of all human action is scarcity, and out of this binary attribute we can deduct a logical framework of individual liberty, property rights and prosperity. footnote:[Mises (1949), Human Action.] Since the concept of money is a tool to allocate scarce resources throughout time, any money must first and foremost be a scarce good. All early cyberspace moneys have failed due to the lack of non-simulated scarcity, footnote:[Lopp (2016), Bitcoin and the Rise of the Cypherpunks.] yet Bitcoin has successfully created what was deemed impossible.

Part one of this thesis is exploring the fundamental axiom of scarcity, and how this conflict of exclusion leads to the need for property rights to manage resource allocation and mutually beneficial exchange amongst individuals. The opposite polarity of non-scarcity is evident in the dealings of the mind and cyberspace where knowledge can be shared freely amongst peers. footnote:[[Hillebrand (2018), Anarchy in Money and the chapter on Scarcity.] Cryptography in general, and Bitcoin specifically, are concepts that utilize both scarce and non-scarce goods to create fascinating tools to remove uneasiness. Although Bitcoin, the network, is in non-scarce cyberspace, the individual bitcoin, the unspent transaction output, is fundamentally scarce, thus enabling non-simulated property rights in this libre sound money.

== Scarcity

Scarcity is the binary attribute of exclusivity of an economic good. When Alice holds a gold coin in her hand, she has full control over it and can use it throughout time and space. At the same time, Bob can not have the same coin and do something different with it. It's either Alice, or Bob, who can enjoy the experience of having the gold coin at their full disposal, but not both of them at the same time. Only one can use this good to solve problems, and even though the other might need the good, he cannot utilize it at all. Alice has to sacrifice the usage of the coin, in order that Bob can have it. Scarcity applies to anything and everything that cannot be simultaneously owned, one's ownership excludes others. Scarcity is an unwavering natural constraint on these economic goods, yet it is neither negative nor positive, but it is neutral and natural. 


Notice that scarcity has nothing to do with the total quantity of a good in existence. A single corn of sand is absolutely scarce, either Alice or Bob has it. The fact that there is countless more sand does not remove the conflict of ownership over that specific sand corn Alice is holding. Air is abundant on this earth, and since the supply is so high, it seems there is no need to economize the scarce air, thus there is usually not property rights in air, or a price for air in exchange. Yet under water the quantity of air is drastically limited, and this shows that air is absolutely scarce. One air tank can only be used by only one scuba-divers at one time, it is absolutely impossible that one tank can sustain two divers. It is clear that the scarce air in the tanks must now be allocated efficiently throughout time.

_“Only because scarcity exists is there even a problem of formulating moral laws; insofar as goods are superabundant (‘free’ [non-scarce] goods), no conflict over the use of goods is possible  and  no  action-coordination is needed”_ footnote:[Hoppe, (1989) Theory of Socialism and Capitalism, p.158, n.120.] Since only one individual alone can at any time use the scarce good, there needs to be an economic and moral principle to allocate the resources to their rightful owner. There are three logical systems that might be applied: Individual Liberty with private property; Slavery with a master and slave class; or Communism with collective ownership.

== Liberty

=== Private Property

The function of property rights is to mitigate interpersonal conflict by defining one specific and exclusive owner of each scarce resource. With property rights, it is always clear who owns what, and more importantly, what one is not allowed to use, specifically not the property of someone else. These property rights must be both visible and just, since otherwise they could not function their task to mitigate conflict. One individual can only know that a specific good is owned by another, if he has advertised this clearly. Thus, the definition of property rights must be universal, objective and unambiguous. footnote:[Hillebrand, (2018). Anarchy in Money, Chapter 1 on Natural Law.]

=== Homesteading

Scarce resources are abundantnin nature and the first individual to occupy a previously unused good and intermingle his human ingenuity to create higher order goods has homesteaded it and thus acquired the just property rights. _Whatsoever, then, he removes out of the state that Nature hath provided and left it in, he hath mixed his labor with it, and joined to it something that is his own, and thereby makes it is property._ footnote:[Locke, (1689) The Two Treatises of Government.] Since natural resources are unowned and not used by anyone, the homesteader does not harm anyone else by occupying these goods. Contrarily, with these goods at disposal, the homesteader has the means to remove problems in his uncertain future, thus marginally increasing his subjective values. Because nobody looses, and the homesteader gains, this act is in accordance to the Natural Law of Non-Aggression. 

=== Mutually Beneficial Exchange

Since property rights mean full and ultimate individual control over a scarce good, he can exchange the right to use these goods with one another. footnote:[See Rothbard (1964) Man Economy and State With Power and Markets, Chapter 2 Part 4 Terms of Exchange.] When two peers are exchanging scarce resources, Alice is sacrificing her property in that good, she is giving up the current and future enjoyment and prosperity of it. In order to compensate her for this loss, she will want to have something in return, a good or service being offered by Bob. And only when she values Bobs exchanged good marginally higher than she values her previous good, will she voluntarily agree to the trade. The same is true for Bob, but in reverse order. He will only trade if Alices good is of higher marginal subjective value than the good he is sacrificing. Only because of this asymmetry of needs and desires will the two peers voluntarily choose to trade their goods, and only then it is mutually beneficial. Although both have sacrificed and lost access to a good, they have both gained marginally more, and are thus better of. Since nobody was harmed, there was no aggression and no violation to Natural Law.

Homesteading and mutually beneficial voluntary exchange are the only ways of justly acquiring the property rights in a scarce good. Anyone who is aggressively and without consent taking away a justly acquired good from another, is politically breaking private property rights in that scarce good. 

_"The argument for property rights is based [...] on the need of individuals to employ means to achieve ends, and to avoid interpersonal conflict over such means. This scarcity is [...] a necessary background condition that must obtain before property rights can emerge."_ footnote:[Kinsella (2008) Against Intellectual Property, p. 40.] Scarcity is the fundamental per-requisite of any money, as there can not be a store of value, medium of exchange and unit of account without property rights, as this good could be copied ad infinitum.

== Slavery

In a system of slavery there exists two distinct classes of individuals: the master class who has property rights, and the slave class who has not. The tyrant has the legal right to exclusive ownership for all his homesteaded and exchanged scarce goods and his human slaves. He has the full benefit of their human ingenuity to remove problems, and can deploy them in various tasks. For fundamental praxeological analysis, it is not of concern how the master came to rule, through incoherence monarchy, elected democracy or military dictatorship. The tyrant can intervene either autistic, binary or triangular.

=== Autistic Intervention

In autistic intervention footnote:[Rothbard (1962), Power and Markets, Chapter 2 Fundamentals of Intervention] the master denies the slave the peaceful use of a scarce good. For example during prohibition the tyrant aggresses against a slave who is himself consuming a good like alcohol without permission. The master claims a higher right in the slaves body and action, than the right of the individual. The master gains in the satisfaction of obedience and by the inaction of his slave, he only looses the opportunity cost of not enforcing the intervention. The slave looses due to the lack of problem solving, as well as through the direct and indirect aggression of the master, yet he gains nothing. He looses regardless his intention to adhere to the man made law, since even if he would voluntarily choose to comply, he is still subject to the implied coercion by the master. This is contrary to a free market of voluntary interaction, where the individual would be suggested and persuaded to stop the action non coercively without the thread of violence. Yet the free individual can at of course deny the advice and continue allocating his scarce resources in the way he intended.

=== Binary intervention

A tyrant can enforce binary intervention footnote:[Rothbard (1962), Power and Markets, Chapter 4 Binary Intervention: Taxation and 5 Binary Intervention: Government Expenditures] by coercing an individual to interact with the state. This can be the involuntary expropriation of scarce goods or scarce labor. The master gains in the products and services stolen, and only sacrifices the opportunity cost of not enforcing the taxation. The slave looses the scarce good, the opportunity cost of acquiring this good, and the implied coercion. In any case, the master gains at the expense of the slave, he constantly applies aggression and coercion and claims property rights in the person and goods of the individual slave. Since this action is not voluntary, it is praxeological proof that it is not mutually beneficial. Even though the state might use some of the stolen property to sustain the slaves, like food, shelter or health care, these goods are not desired marginally most, since they have not voluntarily chosen. This is, of course, in stark contrast to a free market with only mutual beneficial exchange.

=== Triangular intervention

In triangular intervention footnote:[Rothbard (1962), Power and Markets, Chapter 3 Triangular Intervention] the tyrant aggresses against two slaves who do not ask for permission to engage in trade amongst them. Through some form of licensing, registration or forced contract covenants, the state prescribes the way two peaceful individuals must act, and if they fail to comply, then he evicts some punishment. The attack is either in form of price control, or product control. A minimum price artificially excludes clients who don't value the good that high, and entrepreneurs who would already prefer the exchange below minimum price. Since this is inherently not mutually beneficial, it destroys capital and prosperity, while benefiting the master only. When manipulating the nature of production directly, rather than the terms of exchange, the building or sale of certain scarce goods is prohibited. Again, both client and entrepreneur are artificially prohibited from removing their problems and increasing their subjective marginal value scale, yet the master gains in the pleasure of submission.

== Communism

Communism is the utopia of shared ownership of scarce means of production. The workers shall collectively use the tools at their disposal to remove problems, from each according to his ability, to each according to his needs. footnote:[Marx (1875), Critique of the Gotha Program.] Yet this disregards the universal truth of exclusivity of scarce goods. The workers cannot collectively own the scarce means of production, since they are scarce, and thus only one individual at one time can use them. Communism neglects the need to allocate scarce resources throughout time, and thus inevitably will lead to capital destruction and misery. footnote:[Mises (1951), Socialism: An Economic and Sociological Analysis] The ideal of sharing goods with others, although not feasible in the realm of scarcity, is not just doable, but desirable with non-scarce goods.

== Non-Scarcity

The polar opposite manifestation of this attribute is non-scarcity, goods that can be copied ad infinitum without degrading the quality of the original. footnote:[See Kinsella, (2008) Against Intellectual Property.] Due to this super-abundance these good are not subject to desire and choice, as they exist in superfluity, they gratify and also satisfy all desires which depend on their use. footnote:[See Fetter, (1915) Economic Principles, Chapter 1, §3.] They are non-exclusive, thus anyone who desires access and use, can gain this without taking it from another.

When based on her previous experiences Alice formulates a thought, and speaks this into existence to Bob, this information forces itself into Bob's possession. He can now contemplate what Alice is trying to convey and act upon the information. Bob has clearly gained possession and usage of a good, this can help him remove uneasiness and thus increase his subjective valuation. He only sacrificed the opportunity cost of listening to Alice, yet he gains tremendously by this new knowledge. Alice still has her "original" idea in mind, she can further think on it and share it with others, nothing has been taken away from her. Rather, She can now accumulate new information based on Bob's reaction and use this input to advance and refine her idea. _“When speaking words, they can be taken all to oneself, yet leave all to others and unless the memory fades away, everyone who can hear those words, can take them all and go on each separate way.”_ footnote:[Wills, (1999) St. Augustine, p. 145.]

== Libre Open Source Software

Early cypherpunks had a thorough understanding of the axiom of scarcity, and they strived to create a second realm in cyberspace where non-scarce knowledge can be shared freely and without permission. Nobody could possibly own the 0's and 1's that make up the computer code, just as nobody could exclusively use a certain pattern of words. Especially digital data can be copied at rapid speed for barely any computing cost, and shared across a global network of nodes. Anyone who would like to gain access of a certain set of data, can request a copy without decreasing the quality of the dataset of the originator.

The rational conclusion of the non-exclusivity of software is that the user shall have full access to the source code, and that nobody has the right to aggress against him for copying and adapting the code. _"'Free Software' means that the user has the freedom to run, copy, distribute, study, change and improve the software."_ footnote:[Gnu Project, What is Free Software.] This implies the ability to run the program in whatever way possible and for whatever purpose, since regardless how the software is used, this is of no concern to the author. Changing the individual implementation of the software does not meddle with the copy of other peers, thus there is no harm in forking the code to solve a different task than originally intended. The source code must be open and accessible in order for the user to study and verify what the computation is doing. And this includes the ability to share the knowledge with whomever may request it, both the original, and the forked version. Only when the improvements to the code are made public can everyone benefit from them by updating their code, the right to learn and share what one learns with others.


== Fallacy of Intellectual Property

As there is no potential conflict of control, there is no need to organize the structure of production with these non-scarce goods, because any entrepreneur who would need the good to advance the process could simply copy it. There does not need to be a direct exchange, because the original creator does not give up anything, he still retains his version without any sacrifice. _"But sharing isn't immoral — it's a moral imperative. Only those blinded by greed would refuse to let a friend make a copy."_ footnote:[Swartz, (2008) Guerilla Open Access Manifesto.] “These  designs – the  recipes, the formulas, the ideologies – are the primary thing; they transform the original factors – both human and nonhuman – into means.”_ footnote:[Mises, (1949) Human Action, p. 142.]

Because there is no need to ration the allocation of non-scarce goods, property rights do not emerge. There is no individual ownership of ideas, recipes or music, rather, anyone who is interested can acquire and use this information without taking it from some one else. Information belongs in the universal field of knowledge from where any individual can draw everything needed to understand the truth and apply it in ones life. 

There are currently several different types of "intellectual property" [patents, licenses, non disclosure agreements, ...]. They all claim that the "creator" of a specific idea, recipe or thought are to be the sole beneficiary of it. Anyone who is using this idea on its own, without the explicit consent of the "original thinker" is breaking their property rights and thus punishment is justified and desired. 

Of course this is flawed on a fundamental level. All forms of intellectual creations are per definition non scarce, that is that when the information is shared with others, the "original" producer does not sacrifice the enjoyment of the thought. Precisely because there is no need for resource allocation, there is no need for property rights. IP thus tries to introduce artificial scarcity in a place where nature has granted us non scarcity! It is aggression against the possibility of sharing new knowledge with anyone who needs it, without taking anything from anyone else. The knowledge differential in the hierarchy of peers increases and is thus more prone to attacks. This is an unnecessary limit on the prosperity humans can achieve.

Furthermore, because this bogus claim to establish property rights where we do not need them, innocent individuals get violated in their legit property rights. If Alice comes up with the idea to bake an apple cake, and she registered heir IP claim, when Bob on his own discovers the same recipe, he has not taken anything away from Alice. But because Alice has the power of the State, she can enforce her wrong IP claim an steal the cake from Bob. She has no property right whatsoever in the goods and services that Bob has produced on his own, yet with IP, she can justify her aggressions against a peaceful individual.

_"Natural scarcity is that which follows from the relationship between man and nature. Scarcity is natural when it is possible to conceive of it before any human, institutional, contractual arrangement. Artificial scarcity, on the other hand, is the outcome of such arrangements. Artificial scarcity can hardly serve as a justification for the legal framework that causes the scarcity. Such an argument would be completely circular. On the contrary, artificial scarcity itself needs a justification."_ footnote:[Bouckaert, What is Property? p. 793.] Thus, any form of "intellectual property", be it patents, copyrights or trade marks are completely unjustifiable monopolies of state aggression, privilege and censorship. They are evil to its fundamental core, since it introduces an artificial limit to the potential prosperity humankind might achieve, at the benefit of only a few, but at the expense of many. Those that violently enforce unjust intellectual property, assert control and ownership over some one else's property in scarce resources.

== Non-Scarcity of Cryptography

A cryptographic private key `x` is a very large random number, a piece of non-scarce information which can be copied endlessly without degrading the original. Anyone has the opportunity of independently discovering this particular number, it is impossible to exclude others from utilizing it. Of course, nobody can exclusively use, and thus own a specific number, thus there are no property rights whatsoever in private keys. In cryptography a sufficiently random number can be gained by throwing dice, picking random pages of a book, or utilizing a cryptographically secure random number generator. Because the number field of 2^256 is so large, when one sufficiently random number is picked, it can be assumed that nobody else has knowledge of this specific information.

Whoever has the knowledge of this private key can easily compute a corresponding public key `X` by using a cyclic group `G`, and a generator `g` of `G` to calculate `X = g^x`. Yet with knowledge of only the public key, it is computationally infeasible to calculate the private key. Thus the public key can be shared with others, without revealing any part of the private key itself. In the Pretty Good Privacy protocol footnote:[Zimmermann. Pretty Good Privacy freeware software. 1991.], a static master public keys is used as a long term identity of the key holder. In Bitcoin however, the public key should be used only one time for one payment, and never reused across transactions. footnote:[Belcher. Bitcoin Wiki: Privacy, Address Reuse. 2018.]

To sign a message `m`, a random number `r` and a corresponding nonce `R = g^r`, as well as a hash `c = H(X,R,m)` are computed. The signature `σ` is the tuple `(R,s)` with the nonce `R` and `s = r + cx`. footnote:[Claus-Peter Schnorr. Efficient Signature Generation by Smart Cards. J. Cryptology, 4(3):161–174, 1991.] A signature can thus only be produced with knowledge of the private key `x` and the random nonce `r`, who are both generated at random in a huge number field. The verifier of the signature only needs to have knowledge of the public key `X`, the nonce commitment `R` and the part of the signature `s`. Only when the calculation of `g^s = RX^c` returns valid, did the signer have provable knowledge of the private key.

Asymmetric cryptography assumes that the creator of the private key can keep these bits hidden and occulted from anyone else. Only when this knowledge is exclusively available to the original creator is the signature a conclusive proof of the identity and intent of the signer. However, when some other party copies the non-scarce private keys, he can easily compute a absolutely valid signature, that was not made by the original creator of the keys. It is extremely difficult to keep a private key in the exclusive control of one individual, thus in order to ensure a stable and working protocol, the secure storage and management of private keys is essentially important.

== Scarcity of UTXOs

A Bitcoin unspent transaction output [UTXO] can only be spend when the corresponding redeem script is returned valid, these conditions are expressed in the non-Turing-complete Bitcoin script language. At any time, a UTXO has only one script which commits to the spending conditions, the property right definitions of that bitcoin. Thus, there is a potential conflict over who can use this UTXO, it's either the script of Alice, or that of Bob. For example a pay-to-witness-public-key-hash [P2WPKH] UTXO can only be spent by he who has the knowledge of the committed private key and proves this with a valid signature. If a transaction is proposed with a wrong signature, then the script computes invalid, and the UTXO is thus not advanced to the next script. Possession of the non-scarce information is sufficient to use the absolutely scarce bitcoin. Although nobody owns information of the private key, its knowledge grants the right to own and use this specific coin. This excludes all those without the private key from using the UTXO, creating a potential conflict of control. Thus there is a need for resource allocation of the coins, which is done with the property rights defined in Bitcoin script.

Because the private key can be shared with others without taking the knowledge from someone else, the access rights to the bitcoin can be shared as well. Multiple individuals can have knowledge of the same secret, and thus they have the means to provide a valid signature prof. However, with the single key P2WPKH script, only the first individual to broadcast a valid transaction has ultimate control over the bitcoin on chain. Many peers have potential control over the coin, yet only the first to act has the ultimate ownership of it. Thus, sharing the same private key with others is only a weak simulation of shared ownership.

Pay-to-witness-script-hash [P2WSH] transactions commit to more advanced scripts that can add complexity to the conditions that the spender needs to prove. Such a script could be a multi signature scheme, where `n` private keys are generated individually by different peers. Each of them is the only one to know that specific private key, and they compute the public keys to share them amongst each other. A multi signature redeem script includes all of the `n` public keys, as well as the threshold number of `m` signatures that are required in order to spend the coin. `N` individuals can create their own unique private keys, however, this piece of information alone is worthless, as it cannot be create a valid signature script by it self. Only with the coordination of `m` individuals can the chain of digital signatures be advanced. This is non-simulated shared ownership of the scarce bitcoin which is cryptographically proven and cannot be broken.

=== Double Spending is the Non-Scarcity

A double spending is the aspect of a digital asset to be able to be send several times to different individuals. First, Alice initiates a transaction to Bob, and later, she send the same asset to Charlie, this is an asset that can be double spend, a non-scarce good that is non-exclusive. The main issue is to find a common state of the most current property right definitions, the Byzantines Generals Problem. Bitcoin solves this computer science problem in a decentralized trust less way.

In other words, the ability to spend the same good twice, means that Alice can give a good to Bob, without sacrificing the possession and usage of that good. Thus, this good is non scarce and does not require property rights to allocate resources. Any non scarce good can thus be double spend, while this is impossible for any scarce asset.


=== Bitcoin Halving and Scarcity

Every 210 000 blocks, the issuance rate of new bitcoin in the coin base transaction is halved from the original 50 bitcoin reward. Full nodes will not allow any block that has a coin base reward larger than the halved amount. This means that over time, the stock to flow ratio increases exponentially, until it reaches infinity in the year 2141. It is important to differentiate that this does not at all affect the scarcity of bitcoin. Regardless the quantity of total money supply, one UTXO can only be spend by the one defined script. This is true in the case of a total money supply of 50, 21 million or 84 billion bitcoin. The axiomatic importance is the fact that one UTXO can only be spend by one script, and not two different scripts at the same time. Scarcity is what is needed in order to make a monetary asset possible in the first place. For a medium of exchange, the total supply of money is completely irrelevant, since prices will simply adjust to reflect the market demand of holding money in percentage to the total money supply. footnote:[Hillebrand. Anarchy in Money: Money Supply and Inflation. 2018.]
