= Scarcity

This chapter explains the fundamental reason Why multi signature transactions are one of the breathtaking innovations in Bitcoin. The holistic combination of all the nuances in this consensus network emerge a good which has properties like we have never seen before. Bitcoin brilliantly intermingles attributes of both scarcity and non-scarcity to emerge true shared ownership of a good. footnote:[See my Paper on https://towardsliberty.com/videos/anarchy/[Anarchy in Money] https://github.com/MaxHillebrand/Anarchy-in-Money/blob/master/Scarcity.asciidoc[Chapter 9 on Scarcity]]

== Scarcity

When Alice holds a gold coin in her hand, she has full control over it and can use it throughout time and space. At the same time, Bob can not have the same coin and do something different with it. It's either Alice, or Bob, who can enjoy the experience of having the gold coin at their disposal, but not both of them at the same time. There is a potential of conflict over who can use the gold coin, and we need economic and moral rules that guide our actions in such conditions. _“Only because scarcity exists is there even a problem of formulating moral laws; insofar as goods are superabundant (‘free’ [non-scarce] goods), no conflict over the use of goods is possible  and  no  action-coordination is needed”_ footnote:[Hoppe, (1989) Theory of Socialism and Capitalism, p.158, n.120.] Scarcity applies to anything and everything that cannot be simultaneously owned, one's ownership excludes others.

Because only one individual alone can at any time use the scarce good, there needs to be an economic and moral principle of property rights to allocate the resources to their most needed tasks. Scarce resources are abundant in nature and the first individual to intermingle human ingenuity to create higher order goods has homesteaded this good and acquired the property rights in it. Individuals can exchange the right to use these goods with one another, assuming asymmetric valuefootnote:[See Rothbard (1964) Man Economy and State With Power and Markets, Chapter 2 Part 4 Terms of Exchange.] judgement. Homesteading, production and mutually beneficial voluntary exchange are the only ways of justly acquiring a scarce good. Scarcity is the fundamental pre-requisite of any money, there can not be a medium of exchange which can be copied ad infinitum. Anyone who is aggressively and without consent taking away a justly acquired good from another, is politically breaking private property rights in the scarce good.

== Non-Scarcity

The other manifestation of this attribute is non-scarcity, goods that can be copied ad infinitum without degrading the quality of the original.footnote:[See Kinsella, (2008) Against Intellectual Property.] Due to this super-abundance these good are not subject to desire and choice, as they exist in superfluity, they gratify and also satisfy all desires which depend on their use.footnote:[See Fetter, (1915) Economic Principles, Chapter 1, §3.] 

When based on her previous experiences Alice formulates a thought, and speaks this to Bob, this information forces itself into Bob's possession. He can now contemplate what Alice is trying to convey and act upon the information. Alice still has her original idea in mind, nothing has been taken away from her. Rather, She can now accumulate new information based on Bob's reaction to her. _“When speaking words, they can be taken all to oneself, yet leave all to others and unless the memory fades away, everyone who can hear those words, can take them all and go on each separate way.”_ footnote:[Wills, (1999) St. Augustine, p. 145.]

There is no need to organize the structure of production with these non-scarce goods, because any entrepreneur who would need the good to advance the process could simply copy it. There does not need to be a direct exchange, because the original creator does not give up anything, he still retains his version. _“These  designs – the  recipes, the formulas, the ideologies – are the primary thing; they transform the original factors – both human and nonhuman – into means.”_ footnote:[Mises, (1949) Human Action, p. 142.]

Only those blinded by greed will deny a truth seeking friend to make a copy.





xxxxxxxxxxxxxxxxxxxxxxxxxx
**shared ownership** should be first, otherwise it's just a "simulation", which might be an ok thread model
scaling needs software
**bitcoin is first time that shared ownership is not just a simulation!!!**
shared ownership is voluntary opt in
`M-of-n access rights to node with 2-of-2 payment channels via macaroons, RPC, ...` -- is a simulation