= Scarcity

This chapter explains the fundamental reason Why multi signature transactions are one of the breathtaking innovations in Bitcoin. The holistic combination of all the nuances in this consensus network emerge a good which has properties like we have never seen before. Bitcoin brilliantly intermingles attributes of both scarcity and non-scarcity to emerge true shared ownership of a good. footnote:[See my Paper on https://towardsliberty.com/videos/anarchy/[Anarchy in Money] https://github.com/MaxHillebrand/Anarchy-in-Money/blob/master/Scarcity.asciidoc[Chapter 9 on Scarcity]]

== Scarccity

When Alice holds a gold coin in her hand, she has full control over it and can use it throughout time and space. At the same time, Bob can not have the same coin and do something different with it. It's either Alice, or Bob, who can enjoy the experience of having the gold coin at their disposal, but not both of them at the same time. There is a potential of conflict over who can use the gold coin, and we need economic and moral rules that guide our actions in such conditions. _“Only because scarcity exists is there even a problem of formulating moral laws; insofar as goods are superabundant (‘free’ [non-scarce] goods), no conflict over the use of goods is possible  and  no  action-coordination is needed”_ footnote:[Hoppe, (1989) Theory of Socialism and Capitalism, p.158, n.120.] Scarcity applies to anything and everything that cannot be simultaneously owned, one's ownership excludes others.

Because only one individual alone can at any time use the scarce good, there needs to be an economic and moral principle to allocate the resources to their most needed tasks. Scarce resources are abundant in nature and the first to intermingle human ingenuity to create higher order goods has homesteaded this good and acquired the property rights in it. Individuals can exchange the right to use these goods with one another, assuming asymmetric value judgement. Homesteading, production and mutually beneficial voluntary exchange are the only ways of justly acquiring a scarce good. Scarcity is the fundamental pre-requisite of any money, there can not be a medium of exchange which can be copied ad infinitum. Anyone who is aggressively and without consent taking away a justly acquired good from another, is politically breaking private property rights in the scarce good.

