== Threshold Signatures

A threshold signature scheme footnote:[Stinson, Strobl. Provably Secure Distributed Schnorr Signatures and a (t,n) Threshold Scheme for Implicit Certificates. Certicom Corporation, 2001.] is setup by n individual public keys, and it computes valid only with proof of knowledge of m private keys.

This uses in part Shamir's Secret Sharing Scheme, where a dealer distributes a secret `MS` to `n` peers so that any group of `m` peers can reconstruct the `MS`, yet any group `m-1` does not get any information about `MS`. footnote:[See Chapter on Shamir's Secret Sharing Scheme]

=== Key Generation

All `n` signers compute their individual private public key pairs, and they use a `m-of-n` verifiable secret sharing scheme footnote:[See Chapter on Shamir's Secret Sharing Scheme] to generate `n` shares of their individual private key, so that given `m` shares the individual private key can be calculated. Each of the `n` participants then give each peer one specific share, so that all peers have one share each of all the private keys of all participants. Due to the linearity of the Schnorr signature scheme, these shares can be added, or tweaked to the individual private key. All participants broadcast their individual public keys, so that an n-of-n aggregated public key `Ẋ` can be calculated and used as the locking script of a UTXO. footnote:[See Chapter on Schnorr Signatures, Part on Interactive Key Aggregation]

=== Signing

In order to produce a valid signature, at least `m` participants need to collaborate. Each of them signs a spending transaction with the individual tweaked private key, which is the sum of their individual private key and all `n-1` shares of the other individual private keys. All `m` individual signatures are then aggregated to the final signature. This includes the `m` "full" signatures of each active signer, and `m` shares of the signature of the `n-m` non-signing private keys. Because `m` shares are enough to produce the full signature for the non-signing keys, this final signature is thus a fully n-of-n, and thus valid according to regular MuSig.
