
Types of Transaction
====================

A bitcoin is the tip of the chain of digital signatures which originates in the coinbase issuance transaction. A transaction dedicates inputs, which are previously unspent transaction outputs with a valid ScriptPubKey; and outputs, which link the bitcoin to a new ScriptPubKey.

Pay to Public Key Hash
----------------------

A ScriptPubKey is a short script that details the conditions which must be met in order to claim control of the bitcoin. In a **P2PKH** transaction, this script contains `OP_DUP OP_HASH160 <PubKey> OP_EQUALVERIFY OP_CHECKSIG`, the UTXO can only be spend by the proof of knowledge of the private key corresponding to the commited public key hash. The signature script is a prefixed to the ScriptPubKey and contains an secp256k1 signature and the full public key: `<Sig> <PubKey> OP_DUP OP_HASH160 <PubkeyHash> OP_EQUALVERIFY OP_CHECKSIG`. To verify the correctness of the transaction, all operators from both the Alice's signature and Bob's pubkey script are executed.

Pay to Script Hash
------------------

The ScriptPubkey of a **P2SH** transaction contains a hash of a redeem script, which can be any script whatsoever.footnote:[BIP16] The conditions to redeam the transaction are with the redeemer, not the sender of the transaction. To spend the UTXO, Bob needs to provide the signature with the full redeem script in the signature script. It is only valid, when the redeem script hashes to the same value as the script hash Alice put in the output. The redeem script has the same attributes as a pubkey hash, thus the follow up process is identical to a P2PKH script.

Pay to Witness Public Key Hash
------------------------------

Segregated witnessfootnote:[BIP141] **P2WPKH** transactions remove the signature in the input field, and relocate it in the witness structure of the scriptSig. The script PubKey thus contains only `0 <PubKeyHash>` and the signature is verified as `<signature> <pubkey> CHECKSIG`.

Pay to Witness Script Hash
--------------------------

Similar to P2WPKH, **P2WSH** removes the witness part from the transaction merke tree of the redeem script. The witness part contains for example `0 <signature1> <1 <PubKey1> <PubKey2> 2 CHECKMULTISIG>` and the ScriptPubKey of `0 <ScriptHash>`.
